from pathlib import Path

base = Path(r"c:\Users\yasmitha\OneDrive\internship\python\classes&objects")

rename_map = {
    'set1_01_student_class.Py': 'student_with_name_age_course.Py',
    'set1_02_car_class.Py': 'car_three_objects_with_details.Py',
    'set1_03_employee_class.Py': 'employee_basic_class.Py',
    'set1_04_mobile_class.Py': 'mobile_brand_model_price.Py',
    'set1_05_book_class.Py': 'two_books_details.Py',
    'set1_06_laptop_class.Py': 'laptop_brand_ram_processor_price.Py',
    'set1_07_college_class.Py': 'three_college_objects.Py',
    'set1_08_product_class.Py': 'product_with_name_price_quantity.Py',
    'set1_09_bankaccount_class.Py': 'bank_account_details.Py',
    'set1_10_movie_class.Py': 'two_movies_details.Py',
    'set2_01_student_class.Py': 'three_student_objects_list.Py',
    'set2_02_employee_class.Py': 'five_employee_objects_list.Py',
    'set2_03_product_class.Py': 'product_total_price_method.Py',
    'set2_04_car_class.Py': 'three_car_objects_with_values.Py',
    'set2_05_person_class.Py': 'two_person_objects_info.Py',
    'set2_06_book_class.Py': 'multiple_book_objects.Py',
    'set2_07_laptop_class.Py': 'three_laptops_details.Py',
    'set2_08_bankaccount_class.Py': 'two_bank_accounts_details.Py',
    'set2_09_teacher_class.Py': 'multiple_teacher_objects.Py',
    'set2_10_hospital_class.Py': 'three_patient_records.Py',
    'set3_01_student_classvariable.Py': 'student_class_variable_college_name.Py',
    'set3_02_employee_classvariable.Py': 'employee_class_variable_company_name.Py',
    'set3_03_car_classvariable.Py': 'car_class_variable_wheels.Py',
    'set3_04_bankaccount_classvariable.Py': 'bank_account_class_variable_bank_name.Py',
    'set3_05_product_classvariable.Py': 'product_class_variable_category.Py',
    'set3_06_object_counter.Py': 'student_object_counter.Py',
    'set3_07_student_class_and_instance.Py': 'student_class_and_instance_variables.Py',
    'set3_08_employee_classvariables.Py': 'employee_class_variables_company_and_count.Py',
    'set3_09_car_classvariables.Py': 'car_class_and_instance_variables.Py',
    'set3_10_course_classvariable.Py': 'course_class_variable_institute_name.Py',
    'set4_01_student_display_method.Py': 'student_display_method.Py',
    'set4_02_employee_display_salary.Py': 'employee_display_salary_method.Py',
    'set4_03_calculator_methods.Py': 'calculator_methods_add_subtract_multiply_divide.Py',
    'set4_04_rectangle_methods.Py': 'rectangle_area_perimeter_methods.Py',
    'set4_05_circle_methods.Py': 'circle_area_circumference_methods.Py',
    'set4_06_bankaccount_methods.Py': 'bank_account_deposit_withdraw_methods.Py',
    'set4_07_car_methods.Py': 'car_start_stop_display_methods.Py',
    'set4_08_student_marks_methods.Py': 'student_total_average_marks.Py',
    'set4_09_employee_annual_salary.Py': 'employee_annual_salary_method.Py',
    'set4_10_product_total_cost.Py': 'product_total_cost_method.Py',
    'set5_01_student_init.Py': 'student_init_name_age_course_marks.Py',
    'set5_02_employee_init.Py': 'employee_init_employee_id_details.Py',
    'set5_03_book_init_display.Py': 'book_init_and_display_method.Py',
    'set5_04_car_init_methods.Py': 'car_init_start_stop_display_methods.Py',
    'set5_05_bankaccount_init.Py': 'bank_account_init_with_balance.Py',
    'set5_06_product_init_totalprice.Py': 'product_init_total_price_method.Py',
    'set5_07_student_grade.Py': 'student_grade_calculator.Py',
    'set5_08_movie_init_display.Py': 'movie_init_and_display_method.Py',
    'set5_09_laptop_init_display.Py': 'laptop_init_and_display_method.Py',
    'set5_10_hospitalpatient_init.Py': 'hospital_patient_init_and_display_method.Py',
    'set6_01_calculator_parameter_methods.Py': 'calculator_methods_with_parameters.Py',
    'set6_02_student_grade_method.Py': 'student_grade_method_with_marks.Py',
    'set6_03_rectangle_area_method.Py': 'rectangle_area_method_with_dimensions.Py',
    'set6_04_bankaccount_deposit_method.Py': 'bank_account_deposit_method.Py',
    'set6_05_product_total_price_method.Py': 'product_total_price_method_with_quantity.Py',
    'set6_06_employee_salary_method.Py': 'employee_salary_calculation_method.Py',
    'set6_07_number_methods.Py': 'number_even_odd_prime_palindrome.Py',
    'set6_08_string_operations.Py': 'string_reverse_vowel_count_palindrome.Py',
    'set6_09_shopping_cart.Py': 'shopping_cart_add_remove_total.Py',
    'set6_10_temperature.Py': 'temperature_converter_methods.Py',
    'set7_01_class_and_instance_variables.Py': 'class_and_instance_variables_demo.Py',
    'set7_02_multiple_instance_methods.Py': 'method_calls_another_method.Py',
    'set7_03_method_returns_object_info.Py': 'method_returns_other_object_info.Py',
    'set7_04_student_object_counter.Py': 'student_auto_count_objects.Py',
    'set7_05_employee_annual_salary.Py': 'employee_annual_salary_from_monthly.Py',
    'set7_06_bankaccount_insufficient_balance.Py': 'bank_account_insufficient_balance_check.Py',
    'set7_07_librarybook_issue_return.Py': 'library_book_issue_and_return.Py',
    'set7_08_shoppingcart_multiple_products.Py': 'shopping_cart_multiple_products_total.Py',
    'set7_09_course_enrolled_students.Py': 'course_enrolled_students_list.Py',
    'set7_10_company_employees.Py': 'company_employee_management.Py',
}

questions = {
    'student_with_name_age_course.Py': '1. Create a Student class with instance variables name, age, and course. Create three student objects.',
    'car_three_objects_with_details.Py': '2. Create a class called Car and create three objects with different values.',
    'employee_basic_class.Py': '3. Create a class called Employee and create an object to represent an employee.',
    'mobile_brand_model_price.Py': '4. Create a class called Mobile with properties for brand, model, and price. Create an object and display the values.',
    'two_books_details.Py': '5. Create a class called Book with properties for title, author, and price. Create two objects and display their details.',
    'laptop_brand_ram_processor_price.Py': '6. Create a class called Laptop with properties for brand, RAM, processor, and price. Create an object and display its details.',
    'three_college_objects.Py': '7. Create a class called College with properties for college name, location, and course. Create three objects.',
    'product_with_name_price_quantity.Py': '8. Create a class called Product with product name, price, and quantity. Create an object and display its information.',
    'bank_account_details.Py': '9. Create a class called BankAccount with account holder name and account number. Create an object and display the details.',
    'two_movies_details.Py': '10. Create a class called Movie with movie name, hero, heroine, and rating. Create two objects and display their details.',
    'three_student_objects_list.Py': '1. Create a Student class with instance variables name, age, and course. Create three student objects.',
    'five_employee_objects_list.Py': '2. Create an Employee class with instance variables name, department, and salary. Create five employee objects.',
    'product_total_price_method.Py': '3. Create a Product class with name, price, and quantity. Calculate the total price for each object.',
    'three_car_objects_with_values.Py': '4. Create a Car class with brand, model, year, and price. Create three objects with different values.',
    'two_person_objects_info.Py': '5. Create a Person class with name, age, and city. Create two objects and display their information.',
    'multiple_book_objects.Py': '6. Create a Book class with title, author, price, and pages. Create multiple book objects.',
    'three_laptops_details.Py': '7. Create a Laptop class with brand, ram, storage, and price. Create three objects.',
    'two_bank_accounts_details.Py': '8. Create a BankAccount class with account_holder, account_number, and balance. Create two objects.',
    'multiple_teacher_objects.Py': '9. Create a Teacher class with name, subject, and experience. Create multiple teacher objects.',
    'three_patient_records.Py': '10. Create a Hospital class with patient name, age, disease, and doctor name. Create three patient objects.',
    'student_class_variable_college_name.Py': '1. Create a Student class with a class variable college_name. Create three student objects and display the college name.',
    'employee_class_variable_company_name.Py': '2. Create an Employee class with a class variable company_name. Display the company name for multiple employees.',
    'car_class_variable_wheels.Py': '3. Create a Car class with a class variable number_of_wheels. Display it using different objects.',
    'bank_account_class_variable_bank_name.Py': '4. Create a BankAccount class with a class variable bank_name. Create multiple accounts.',
    'product_class_variable_category.Py': '5. Create a Product class with a class variable category. Create different product objects.',
    'student_object_counter.Py': '6. Create a class variable that counts the total number of objects created for a class.',
    'student_class_and_instance_variables.Py': '7. Create a Student class with a class variable representing the school/college name and an instance variable representing the student\'s name.',
    'employee_class_variables_company_and_count.Py': '8. Create an Employee class with class variables company_name and employee_count.',
    'car_class_and_instance_variables.Py': '9. Create a Car class with class variables company and number_of_wheels, and instance variables model and price.',
    'course_class_variable_institute_name.Py': '10. Create a Course class with a class variable institute_name and instance variables course_name and duration.',
    'student_display_method.Py': '1. Create a Student class with a method display() to display student details.',
    'employee_display_salary_method.Py': '2. Create an Employee class with a method display_salary() to display employee salary.',
    'calculator_methods_add_subtract_multiply_divide.Py': '3. Create a Calculator class with methods for addition, subtraction, multiplication, and division.',
    'rectangle_area_perimeter_methods.Py': '4. Create a Rectangle class with methods to calculate area and perimeter.',
    'circle_area_circumference_methods.Py': '5. Create a Circle class with methods to calculate area and circumference.',
    'bank_account_deposit_withdraw_methods.Py': '6. Create a BankAccount class with methods deposit() and withdraw().',
    'car_start_stop_display_methods.Py': '7. Create a Car class with methods start(), stop(), and display_details().',
    'student_total_average_marks.Py': '8. Create a Student class with methods to calculate total marks and average marks.',
    'employee_annual_salary_method.Py': '9. Create an Employee class with a method to calculate annual salary.',
    'product_total_cost_method.Py': '10. Create a Product class with a method to calculate the total cost based on price and quantity.',
    'student_init_name_age_course_marks.Py': '1. Create a Student class using __init__() to initialize name, age, course, and marks.',
    'employee_init_employee_id_details.Py': '2. Create an Employee class using __init__() to initialize employee ID, name, department, and salary.',
    'book_init_and_display_method.Py': '3. Create a Book class using __init__() and a method to display book information.',
    'car_init_start_stop_display_methods.Py': '4. Create a Car class using __init__() and methods start(), stop(), and display().',
    'bank_account_init_with_balance.Py': '5. Create a BankAccount class using __init__() with account holder, account number, and initial balance.',
    'product_init_total_price_method.Py': '6. Create a Product class using __init__() and a method to calculate the total price.',
    'student_grade_calculator.Py': '7. Create a Student class using __init__() and a method to calculate grade based on marks.',
    'movie_init_and_display_method.Py': '8. Create a Movie class using __init__() and a method to display movie information.',
    'laptop_init_and_display_method.Py': '9. Create a Laptop class using __init__() and a method to display complete specifications.',
    'hospital_patient_init_and_display_method.Py': '10. Create a HospitalPatient class using __init__() and a method to display patient information.',
    'calculator_methods_with_parameters.Py': '1. Create a Calculator class with methods that accept parameters and return calculation results.',
    'student_grade_method_with_marks.Py': '2. Create a Student class with a method that accepts marks and returns the grade.',
    'rectangle_area_method_with_dimensions.Py': '3. Create a Rectangle class with a method that accepts length and width and returns the area.',
    'bank_account_deposit_method.Py': '4. Create a BankAccount class with a method that accepts an amount and deposits it into the account.',
    'product_total_price_method_with_quantity.Py': '5. Create a Product class with a method that accepts quantity and returns the total price.',
    'employee_salary_calculation_method.Py': '6. Create an Employee class with a method that accepts working days and calculates salary.',
    'number_even_odd_prime_palindrome.Py': '7. Create a Number class with methods to check whether a number is even, odd, prime, or palindrome.',
    'string_reverse_vowel_count_palindrome.Py': '8. Create a StringOperations class with methods to reverse a string, count vowels, and check palindrome.',
    'shopping_cart_add_remove_total.Py': '9. Create a ShoppingCart class with methods to add products, remove products, and calculate the total.',
    'temperature_converter_methods.Py': '10. Create a Temperature class with methods to convert Celsius to Fahrenheit and Fahrenheit to Celsius.',
    'class_and_instance_variables_demo.Py': '1. Create a class with both class variables and instance variables and demonstrate the difference between them.',
    'method_calls_another_method.Py': '2. Create a class with multiple instance methods where one method calls another method.',
    'method_returns_other_object_info.Py': '3. Create a class with a method that returns another object\'s information.',
    'student_auto_count_objects.Py': '4. Create a Student class that automatically counts how many student objects have been created.',
    'employee_annual_salary_from_monthly.Py': '5. Create an Employee class that automatically calculates annual salary from monthly salary.',
    'bank_account_insufficient_balance_check.Py': '6. Create a BankAccount class that prevents withdrawal when the balance is insufficient.',
    'library_book_issue_and_return.Py': '7. Create a LibraryBook class with methods to issue and return a book.',
    'shopping_cart_multiple_products_total.Py': '8. Create a ShoppingCart class that stores multiple products and calculates the total bill.',
    'course_enrolled_students_list.Py': '9. Create a Course class that stores enrolled students and provides a method to display them.',
    'company_employee_management.Py': '10. Create a Company class that stores employees and provides methods to add, remove, search, and display employees.',
}

# Rename files to descriptive names
for old_name, new_name in rename_map.items():
    old_path = base / old_name
    new_path = base / new_name
    if old_path.exists() and not new_path.exists():
        old_path.rename(new_path)

# Add question comment to each remaining .Py file
for file_path in sorted(base.glob('*.Py')):
    filename = file_path.name
    question = questions.get(filename)
    if not question:
        continue
    original = file_path.read_text(encoding='utf-8')
    if original.startswith('# '):
        continue
    file_path.write_text(f'# {question}\n\n{original}', encoding='utf-8')

print(f'Processed {len(list(base.glob("*.Py")))} Python files in {base}')
