# Generated by Django 6.1.1 on 2026-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=200)),
                ('t_phone', models.CharField()),
                ('t_email', models.CharField()),
            ],
        ),
    ]
